default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: api-blog_development

test:
  <<: *default
  database: api-blog_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: api-blog_production